First stage desktop version
joramot/portfolio-desktop-version pull request #1
Opened 2023-01-21 04:48 UTC by joramot

- Create desktop version of my portfolio according to the requirements list.
- First implementation of media queries
- Implement Animations and transitions

2023-01-21 05:03 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @joramot  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Great work using the  Figma design ☑️ 
- Commits are descriptive and meaningful :+1: 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2023-01-21 05:03 UTC, Nyame-Wolf commented on css/style.css
> +    margin-left: 142px;
I suggest you fix the styles of your page. It uses the template, but your CSS is broken. This is how your page appears both on mobile and Desktop
<img width="1680" alt="Screenshot 2023-01-21 at 07 56 49" src="https://user-images.githubusercontent.com/48546992/213844317-ce01abbf-8197-4eef-ab7f-6bd72da1da3e.png">
<img width="425" alt="Screenshot 2023-01-21 at 07 57 05" src="https://user-images.githubusercontent.com/48546992/213844320-73cf055f-f2f8-49fc-b387-ccfca71c37b6.png">

2023-01-26 01:39 UTC, joramot reviewed
Restructure all sections and rename CSS classes whit short names.
Implement Media Queries in all sections.

2023-01-26 01:59 UTC, BregornOriginal approved these changes
## Hi @joramot 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳 🥳 🥳 

## Congratulations! 💯 💯 💯 

![giphy](https://user-images.githubusercontent.com/93630700/214737569-fd31a9c0-e75d-4c5d-b23d-eb3c7ff7436f.gif)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good Pull Request description
✅ Good work making the changes requested by the previous reviewer

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-01-26 04:48 UTC, merged

2023-01-26 21:18 UTC, dhy-612 reviewed
You have done great work.

I didn't find any issue in the animation part. 👍 👍 

Just follow up for next part, 
send it for review 😀